spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account?ApplicationName=IDEA
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /view/users/
      suffix: .jsp
  jpa:
    show-sql: true
server:
  port: 8082
classifier:
  url: http://localhost:8084/classifier
rep:
  operation:
    url: http://localhost:8085/report/operation
  account:
    url: http://localhost:8085/report/account