spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/telegram-service?ApplicationName=IDEA
    username: ${db_user}
    password: ${db_password}
  jpa:
    show-sql: true
bot:
  name: finance_client_bot
  token: ${telegram_token}
server:
  port: 8088
account:
  url: http://account-service:8082/account
classifier:
  url: http://classifier-service:8084/classifier