spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/mail-scheduler-service?ApplicationName=IDEA
    username: ${db_user}
    password: ${db_password}
  jpa:
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      platform: postgres
    properties:
      "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      "org.quartz.jobStore.tablePrefix": "quartz.QRTZ_"
server:
  port: 8087
mail:
  url: http://mail-service:8086/mail
classifier:
  url: http://classifier-service:8084/classifier
account:
  url: http://account-service:8082/account