version: '3.5'
services:
  minio:
    build: minio
    image: finance_minio:1.0.0
    command: server --console-address ":9001" /finance_data
    env_file:
      - minio/minio.env
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - finance_ntwrk
  db:
    build: postgresql
    image: finance_postgresql:1.0.0
    restart: always
    env_file:
      - postgresql/db.env
    ports:
      - "5433:5432"
    networks:
      - finance_ntwrk
  pgadmin:
    build: pgadmin
    image: finance_pgadmin:1.0.0
    restart: always
    env_file:
      - pgadmin/pgadmin.env
    ports:
      - "82:80"
    networks:
      - finance_ntwrk
  swagger-ui:
    build: swagger-ui
    image: finance_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - finance_ntwrk


  account-scheduler-service:
    build: account-scheduler-service
    image: finance_account-scheduler-service:1.0.0
    networks:
      - finance_ntwrk
  account-service:
    build: account-service
    image: finance_account-service:1.0.0
    networks:
      - finance_ntwrk
  classifier-service:
    build: classifier-service
    image: finance_classifier-service:1.0.0
    networks:
      - finance_ntwrk
  report-service:
    build: report-service
    image: finance_report-service:1.0.0
    networks:
      - finance_ntwrk
  telegram-service:
    build: telegram-service
    image: finance_telegram-service:1.0.0
    networks:
      - finance_ntwrk
  mail-scheduler-service:
    build: mail-scheduler-service
    image: finance_mail-scheduler-service:1.0.0
    networks:
      - finance_ntwrk
  mail-service:
    build: mail-service
    image: finance_mail-service:1.0.0
    networks:
      - finance_ntwrk
  proxy:
    build: proxy
    image: finance_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - finance_ntwrk
networks:
  finance_ntwrk:
    name: finance_ntwrk
