= Program for accounting of income and expenses

http://165.232.159.153:81/[OpenAPI]

== Summary
This is application for accounting and planning of your own income and expenses.
The application is developed using microservice architecture.
At this stage, seven microservices have been made:

* *account-service*  - main service which operates with accounts, operations;
* *classifier-service* - service for creating, storing currencies and categories of operations;
* *account-scheduler-service* - service which provides the ability to automatically create transactions;
* *report-service* - transaction reporting service;
* *mail-service* - email reporting service;
* *mail-scheduler-service* - service for scheduling emails with reports;
* *telegram-service* - service for quickly creating an account transaction via telegram application (the service is under testing).

One services are under development:

* *user-service* - user service. Provides security.

The dependency between services can be seen in the https://miro.com/app/board/uXjVOu8eOOU=/?share_link_id=471729910648[diagram].

== Technologies
=== Programming language
* Java 11

=== Frameworks and libraries
* Spring (Spring Boot)
* Hibernate
* Jackson
* Quartz
* Apache POI
* Telegram Bot

=== Protocols
* HTTP
* IP
* SMTP

=== Data base
* PostgreSQL 14

=== Additional tools
* Docker

