= Program for accounting of income and expenses

http://167.99.5.132:81/[OpenAPI]

== Summary
The  application "Program for accounting of income and expenses" is used for tracking income and  expenses. This application has been developed using microservice architecture. Seven microservices have been created:

* *account-service*  - main service for running accounts and operating transactions;
* *classifier-service* - service for creating, storing currencies and categories of operations;
* *account-scheduler-service* - service for creating  transactions automatically;
* *report-service* - service for transaction reporting;
* *mail-service* - service for email reporting;
* *mail-scheduler-service* - service for scheduling emails with reports;
* *telegram-service* - service for quick creating an account transaction via telegram application (the service is in testing period).

The next service is under development:

* *user-service* - service for providing security.

The dependency between services can be seen from the https://miro.com/app/board/uXjVOu8eOOU=/?share_link_id=471729910648[diagram].

== Technologies
=== Programming language
* Java 11

=== Frameworks and libraries
* Spring (Spring Boot)
* Hibernate
* Jackson
* Quartz
* Apache POI
* Telegram Bot

=== Protocols
* HTTP
* IP
* SMTP

=== Data base
* PostgreSQL 14

=== Additional tools
* Docker

