spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/report-service?ApplicationName=IDEA
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8085
