spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/mail-service?ApplicationName=IDEA
    username: ${db_user}
    password: ${db_password}
  jpa:
    show-sql: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: a.tolkach777@mail.ru
    password: ${smtppassword}
    protocol: smtp
    properties:
      "mail.from": a.tolkach777@mail.ru
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
server:
  port: 8086
rep:
  url: http://report-service:8085/report