spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mail?ApplicationName=IDEA
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /view/users/
      suffix: .jsp
  jpa:
    show-sql: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: a.tolkach777@mail.ru
    password: bzL4vAzrTqyrRkg9g12p
    protocol: smtp
    properties:
      "mail.from": a.tolkach777@mail.ru
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
server:
  port: 8086