spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/classifier?ApplicationName=IDEA
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /view/users/
      suffix: .jsp
  jpa:
    show-sql: true
server:
  port: 8084
rep:
  currency:
    url: http://localhost:8085/report/classifier/currency
  category:
    url: http://localhost:8085/report/classifier/operation_category
