spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mail_scheduler?ApplicationName=IDEA
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /view/users/
      suffix: .jsp
  jpa:
    show-sql: true
server:
  port: 8087